version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
  build and deploy:
    jobs:
      filters:
        branches:
          only:
            - circleci-project-setup
        steps:
          - run:
            command: npm start
